name: Run Tool - Tester
on:
  repository_dispatch:
    types:
      - template-tester

env:
  TAG: templatetester
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run-tester:
    name: Run Tool
    runs-on: template-tester
    permissions:
      packages: read

    strategy:
      matrix:
        template: ${{ github.event.client_payload.templates }}
      fail-fast: false

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker rm -f templatetester-${{ matrix.template }} || true
          echo "::add-mask::${{ secrets.RUNNER_IP }}"

      - name: Run
        run: |
          sudo rm -rf /tmp/pufferpanel-tester 
          mkdir -p /tmp/pufferpanel-tester
          sudo chown -R 1000:$(getent group docker | cut -f3 -d:) /tmp/pufferpanel-tester
          docker run --rm --name templatetester-${{ matrix.template }} --network host -v /tmp/pufferpanel-tester:/tmp/pufferpanel-tester -v /var/run/docker.sock:/var/run/docker.sock -u "1000:$(getent group docker | cut -f3 -d:)" ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} --workDir=/tmp/pufferpanel-tester --files=${{ matrix.template }}
